#!/usr/bin/env bash
set -Eeuo pipefail

readonly primary_local_repo=/Users/tibger01/Projects/Fornjot/a_gpu
readonly remote_host=rhel8-VM
readonly remote_repo=/home/tibger01/projects/fornjot/push_gpu
readonly remote_worktree_root=/home/tibger01/projects/fornjot
readonly script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
readonly remote_runner="$script_dir/run_lint.sh"
readonly git_ssh_command='ssh -o BatchMode=yes -o ConnectTimeout=15 -o ServerAliveInterval=30 -o ServerAliveCountMax=4'

local_repo=$primary_local_repo
local_artifact_root=
commit=
attempt_token=
dry_run=0
local_artifact_dir=
expected_worktree=
remote_task_dir=
run_id=
transfer_status=NOT_RUN
remote_run_status=NOT_RUN
collection_status=NOT_RUN
overall_status=INITIALIZING
finalized=0

usage() {
  cat <<'EOF'
Usage: run_remote_lint.sh --commit SHA [--repo PATH] [--attempt-token TOKEN] [--dry-run]

Transfer current committed a_gpu HEAD to a SHA-specific custom ref in the
RHEL8 push_gpu repository, create a retained sibling worktree, prepare it
through make sources, and run TEX Superlint.

Options:
  --commit SHA  Candidate commit; it must resolve to current committed HEAD
  --repo PATH   Selected a_gpu worktree (default: primary a_gpu checkout)
  --attempt-token TOKEN
                Optional retained-worktree discriminator (auto-generated by default)
  --dry-run     Validate locally and print the exact non-mutating plan
  -h, --help    Show this help
EOF
}

write_driver_status() {
  [[ -n ${local_artifact_dir:-} && -d $local_artifact_dir ]] || return 0
  cat >"$local_artifact_dir/driver-status.env" <<EOF
SCHEMA_VERSION=1
RUN_ID=${run_id:-NOT_STARTED}
CANDIDATE_SHA=${candidate:-UNKNOWN}
ATTEMPT_TOKEN=${attempt_token:-UNKNOWN}
REMOTE_HOST=$remote_host
REMOTE_REPO=$remote_repo
REMOTE_WORKTREE=${expected_worktree:-UNKNOWN}
REMOTE_WORKTREE_RETAINED=1
REMOTE_TASK_DIR=${remote_task_dir:-UNKNOWN}
TRANSFER_STATUS=$transfer_status
REMOTE_RUN_STATUS=$remote_run_status
COLLECTION_STATUS=$collection_status
OVERALL_STATUS=$overall_status
EOF
}

on_exit() {
  local status=$?
  if (( ! finalized )) && [[ $overall_status == INITIALIZING ]]; then
    overall_status=EXECUTOR_ERROR
  fi
  write_driver_status || true
  if (( ! dry_run )); then
    printf 'ATTEMPT_TOKEN=%s\n' "${attempt_token:-UNKNOWN}"
    printf 'REMOTE_WORKTREE=%s\n' "${expected_worktree:-UNKNOWN}"
    printf 'REMOTE_WORKTREE_RETAINED=1\n'
    printf 'LOCAL_ARTIFACT_DIR=%s\n' "${local_artifact_dir:-NOT_CREATED}"
    printf 'RHEL8_LINT_DRIVER_STATUS=%s\n' "$overall_status"
    printf 'RHEL8_LINT_DRIVER_EXIT_STATUS=%s\n' "$status"
  fi
}
trap on_exit EXIT

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

git_local() {
  command git -c core.fsmonitor=false "$@"
}

while (($#)); do
  case "$1" in
    --commit)
      (($# >= 2)) || die 'Missing value for --commit.'
      commit=$2
      shift 2
      ;;
    --repo)
      (($# >= 2)) || die 'Missing value for --repo.'
      local_repo=$2
      shift 2
      ;;
    --attempt-token)
      (($# >= 2)) || die 'Missing value for --attempt-token.'
      attempt_token=$2
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      trap - EXIT
      usage
      exit 0
      ;;
    *)
      usage >&2
      die "Unknown argument: $1"
      ;;
  esac
done

[[ -n $commit ]] || die '--commit is required.'
[[ $commit =~ ^[0-9A-Fa-f]{7,40}$ ]] ||
  die '--commit must be a 7-40 digit hexadecimal SHA.'
git_local -C "$primary_local_repo" rev-parse --git-dir >/dev/null 2>&1 ||
  die "Primary local repository is unavailable: $primary_local_repo"
local_repo=$(git_local -C "$local_repo" rev-parse --show-toplevel) ||
  die 'Cannot resolve the selected local repository.'
local_repo=$(cd "$local_repo" && pwd -P)
primary_common_dir=$(git_local -C "$primary_local_repo" rev-parse --path-format=absolute --git-common-dir) ||
  die 'Cannot resolve the primary repository common Git directory.'
selected_common_dir=$(git_local -C "$local_repo" rev-parse --path-format=absolute --git-common-dir) ||
  die 'Cannot resolve the selected repository common Git directory.'
[[ $selected_common_dir == "$primary_common_dir" ]] ||
  die 'Selected repository is not an a_gpu worktree.'
local_artifact_root="$local_repo/private/tmp/to_persist/validation-campaign/wave-a/rhel8-lint"
[[ -f $remote_runner ]] || die "Remote runner is missing: $remote_runner"

candidate=$(git_local -C "$local_repo" rev-parse --verify "$commit^{commit}") ||
  die "Cannot resolve candidate commit: $commit"
head_sha=$(git_local -C "$local_repo" rev-parse --verify 'HEAD^{commit}')
[[ $candidate == "$head_sha" ]] ||
  die "Requested commit is not current HEAD (requested=$candidate HEAD=$head_sha)."
if ! git_local -C "$local_repo" diff --quiet --ignore-submodules=all -- ||
   ! git_local -C "$local_repo" diff --cached --quiet --ignore-submodules=all --; then
  die 'Tracked changes exist; commit or remove them before transferring HEAD.'
fi

short_sha=${candidate:0:12}
candidate_ref="refs/codex/validation-campaign/rhel8-lint/$candidate"
if [[ -z $attempt_token ]]; then
  attempt_token="lint_$(date -u +%Y%m%dT%H%M%SZ)_$$"
fi
[[ $attempt_token =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$ ]] ||
  die 'Rejected attempt token.'
expected_worktree="$remote_worktree_root/tmp_gpu_lint_run_${short_sha}_$attempt_token"
[[ $expected_worktree =~ ^/home/tibger01/projects/fornjot/tmp_gpu_lint_run_[0-9a-f]{12}_[A-Za-z0-9][A-Za-z0-9._-]{0,95}$ ]] ||
  die 'Derived worktree failed its exact-path guard.'

if ((dry_run)); then
  printf 'MODE=DRY_RUN\n'
  printf 'LOCAL_REPO=%s\n' "$local_repo"
  printf 'CANDIDATE_SHA=%s\n' "$candidate"
  printf 'REMOTE_HOST=%s\n' "$remote_host"
  printf 'REMOTE_REPO=%s\n' "$remote_repo"
  printf 'REMOTE_CANDIDATE_REF=%s\n' "$candidate_ref"
  printf 'ATTEMPT_TOKEN=%s\n' "$attempt_token"
  printf 'REMOTE_WORKTREE=%s\n' "$expected_worktree"
  printf 'REMOTE_WORKTREE_RETAINED=1\n'
  printf 'SETUP_BOUNDARY=design/logical/make_sources\n'
  printf 'LINT_COMMAND=dcs_superlint superlint_8x/configuration_top.yaml\n'
  printf 'REMOTE_CHECKOUT_UPDATE=none_custom_ref_only\n'
  printf 'LOCAL_ARTIFACT_ROOT=%s\n' "$local_artifact_root"
  finalized=1
  exit 0
fi

timestamp=$(date -u +%Y%m%dT%H%M%SZ)
run_id="rhel8-lint-$short_sha-$timestamp-$$"
local_artifact_dir="$local_artifact_root/$run_id"
remote_task_dir="$expected_worktree/private/tmp/to_persist/rhel8-lint/$run_id"
mkdir -p "$local_artifact_dir"
cat >"$local_artifact_dir/driver-metadata.env" <<EOF
SCHEMA_VERSION=1
RUN_ID=$run_id
CANDIDATE_SHA=$candidate
ATTEMPT_TOKEN=$attempt_token
REMOTE_HOST=$remote_host
REMOTE_REPO=$remote_repo
REMOTE_CANDIDATE_REF=$candidate_ref
REMOTE_WORKTREE=$expected_worktree
REMOTE_WORKTREE_RETAINED=1
REMOTE_TASK_DIR=$remote_task_dir
SETUP_BOUNDARY=design/logical/make_sources
LINT_COMMAND='dcs_superlint superlint_8x/configuration_top.yaml'
EOF
write_driver_status

ssh_options=(
  -o BatchMode=yes
  -o ConnectTimeout=15
  -o ServerAliveInterval=30
  -o ServerAliveCountMax=4
)
ssh_transport='ssh -o BatchMode=yes -o ConnectTimeout=15 -o ServerAliveInterval=30 -o ServerAliveCountMax=4'

printf 'Checking the fixed RHEL8 push_gpu handoff repository.\n'
remote_top=$(ssh "${ssh_options[@]}" "$remote_host" \
  git -C "$remote_repo" rev-parse --show-toplevel) ||
  die "Cannot inspect remote handoff repository: $remote_repo"
[[ $remote_top == "$remote_repo" ]] ||
  die "Remote handoff repository resolved outside its fixed path: $remote_top"
remote_checkout_head_before=$(ssh "${ssh_options[@]}" "$remote_host" \
  git -C "$remote_repo" rev-parse --verify 'HEAD^{commit}') ||
  die 'Cannot record push_gpu checkout HEAD before transfer.'
remote_checkout_status_before=$(ssh "${ssh_options[@]}" "$remote_host" \
  git -C "$remote_repo" status --porcelain=v1 --untracked-files=no) ||
  die 'Cannot record push_gpu tracked checkout status before transfer.'

printf 'Transferring exact candidate %s to custom ref %s.\n' \
  "$candidate" "$candidate_ref"
set +e
export GIT_SSH_COMMAND=$git_ssh_command
git_local -C "$local_repo" push \
  "$remote_host:$remote_repo" "$candidate:$candidate_ref" 2>&1 |
  tee "$local_artifact_dir/transfer.log"
push_status=${PIPESTATUS[0]}
set -e
if ((push_status != 0)); then
  transfer_status=FAIL
  overall_status=TRANSFER_FAILED
  die "Candidate transfer failed with status $push_status."
fi

remote_candidate=$(ssh "${ssh_options[@]}" "$remote_host" \
  git -C "$remote_repo" rev-parse --verify "$candidate_ref^{commit}") || {
  transfer_status=FAIL
  overall_status=TRANSFER_VERIFICATION_FAILED
  die 'Cannot verify transferred candidate ref.'
}
[[ $remote_candidate == "$candidate" ]] || {
  transfer_status=FAIL
  overall_status=TRANSFER_VERIFICATION_FAILED
  die "Remote candidate mismatch: expected=$candidate actual=$remote_candidate"
}
remote_checkout_head_after=$(ssh "${ssh_options[@]}" "$remote_host" \
  git -C "$remote_repo" rev-parse --verify 'HEAD^{commit}') || {
  transfer_status=FAIL
  overall_status=TRANSFER_VERIFICATION_FAILED
  die 'Cannot record push_gpu checkout HEAD after transfer.'
}
remote_checkout_status_after=$(ssh "${ssh_options[@]}" "$remote_host" \
  git -C "$remote_repo" status --porcelain=v1 --untracked-files=no) || {
  transfer_status=FAIL
  overall_status=TRANSFER_VERIFICATION_FAILED
  die 'Cannot record push_gpu tracked checkout status after transfer.'
}
[[ $remote_checkout_head_after == "$remote_checkout_head_before" &&
   $remote_checkout_status_after == "$remote_checkout_status_before" ]] || {
  transfer_status=FAIL
  overall_status=REMOTE_CHECKOUT_CHANGED
  die 'push_gpu checkout HEAD or tracked status changed during custom-ref transfer.'
}
transfer_status=PASS
overall_status=RUNNING_REMOTE_LINT
write_driver_status

printf 'Creating retained worktree %s and starting TEX Superlint.\n' "$expected_worktree"
set +e
ssh "${ssh_options[@]}" "$remote_host" bash -s -- \
  --commit "$candidate" --run-id "$run_id" --attempt-token "$attempt_token" \
  <"$remote_runner" 2>&1 | tee "$local_artifact_dir/remote-session.log"
remote_run_status=${PIPESTATUS[0]}
set -e

printf 'Collecting executor metadata and logs; the remote worktree remains in place.\n'
set +e
rsync -a -e "$ssh_transport" \
  "$remote_host:$remote_task_dir/" "$local_artifact_dir/" 2>&1 |
  tee "$local_artifact_dir/collect.log"
collect_exit=${PIPESTATUS[0]}
set -e
if ((collect_exit == 0)); then
  collection_status=PASS
else
  collection_status=FAIL
fi

if ((remote_run_status == 0 && collect_exit == 0)); then
  overall_status=COMPLETE
  finalized=1
  write_driver_status
  printf 'RHEL8_LINT_COMPLETE=1\n'
  exit 0
fi

if ((remote_run_status != 0)); then
  overall_status=REMOTE_LINT_FAILED
else
  overall_status=COLLECTION_FAILED
fi
finalized=1
write_driver_status
if ((remote_run_status != 0)); then
  exit "$remote_run_status"
fi
exit 1
